#!/bin/bash

# FTI - Quick Deploy to Render.com (Free)

echo "🚀 FTI Free Deployment Setup"
echo "=============================="
echo ""

# Check if git is initialized
if [ ! -d .git ]; then
    echo "📦 Initializing Git repository..."
    git init
    git add .
    git commit -m "Initial commit - FTI Application"
    echo "✅ Git repository initialized"
else
    echo "✅ Git repository already exists"
fi

echo ""
echo "📋 Next Steps for FREE Deployment:"
echo ""
echo "Option 1: Render.com (Recommended)"
echo "-----------------------------------"
echo "1. Create account: https://render.com"
echo "2. Create GitHub repository and push code:"
echo "   git remote add origin <your-github-repo-url>"
echo "   git push -u origin main"
echo "3. In Render dashboard:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Connect your GitHub repo"
echo "   - Render will auto-detect settings from render.yaml"
echo "4. Add environment variable:"
echo "   MONGO_URI = <your-mongodb-atlas-connection-string>"
echo "5. Click 'Create Web Service'"
echo ""
echo "Option 2: Railway.app"
echo "---------------------"
echo "1. Create account: https://railway.app"
echo "2. Click 'New Project' → 'Deploy from GitHub repo'"
echo "3. Select your repository"
echo "4. Add MongoDB plugin (free)"
echo "5. Add environment variables from .env.example"
echo "6. Deploy automatically"
echo ""
echo "Option 3: Fly.io"
echo "----------------"
echo "1. Install Fly CLI: curl -L https://fly.io/install.sh | sh"
echo "2. Run: fly auth login"
echo "3. Run: fly launch"
echo "4. Follow prompts (select free tier)"
echo ""
echo "🗄️  Free Database Setup (MongoDB Atlas):"
echo "----------------------------------------"
echo "1. Sign up: https://www.mongodb.com/cloud/atlas/register"
echo "2. Create FREE cluster (M0 Sandbox - 512MB)"
echo "3. Create database user"
echo "4. Whitelist IP: 0.0.0.0/0 (allow from anywhere)"
echo "5. Get connection string"
echo "6. Replace <password> and <dbname> in connection string"
echo ""
echo "✨ Your app will be live at: https://your-app-name.onrender.com"
echo ""
echo "💡 Tips:"
echo "- Free tier sleeps after 15 min inactivity"
echo "- First request after sleep takes ~30 seconds"
echo "- Upgrade to paid tier ($7/month) for always-on"
echo ""
echo "📚 Full guide: See DEPLOYMENT_FREE.md"
